#!/usr/local/bin/ruby

# = Populate Redis
# 
# 
# Usage:
# 
#     $ populate-redis 1000
#     $ populate-redis --flushdb 1000
#
#--

require 'benchmark'
require 'redis'

REDISURI = 'redis://localhost:6371/0'
FLUSHDB = ARGV.member?('--flushdb') && ARGV.shift
TIMES = (ARGV.last || 1_000_000).to_i

redis = Redis.connect :url => REDISURI
now = Time.now.utc.to_i
if FLUSHDB
  puts "Flushing db..."
  redis.flushdb
end
puts "Generating..."
time = Benchmark.measure do
  redis.pipelined do
    TIMES.times do |idx|
      grp = idx % 10
      redis.set 'rdtemp:%d:idx-%d:group-%d' % [now, idx, grp], '0' * (rand*1000).to_i
    end
  end
end
info = redis.info
puts '%s in %s' % [info['db0'], redis.client.id]
puts 'Used memory: %s' % [info['used_memory_human']]
puts time.to_s

